[pytest]
pythonpath = .
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
    ignore::sqlalchemy.exc.MovedIn20Warning
    ignore::pydantic.PydanticDeprecatedSince20
